require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/findingaids", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Findingaid. As you add validations to Findingaid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Findingaid.create! valid_attributes
      get findingaids_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      findingaid = Findingaid.create! valid_attributes
      get findingaid_url(findingaid)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_findingaid_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      findingaid = Findingaid.create! valid_attributes
      get edit_findingaid_url(findingaid)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Findingaid" do
        expect {
          post findingaids_url, params: {findingaid: valid_attributes}
        }.to change(Findingaid, :count).by(1)
      end

      it "redirects to the created findingaid" do
        post findingaids_url, params: {findingaid: valid_attributes}
        expect(response).to redirect_to(findingaid_url(Findingaid.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Findingaid" do
        expect {
          post findingaids_url, params: {findingaid: invalid_attributes}
        }.not_to change(Findingaid, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post findingaids_url, params: {findingaid: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested findingaid" do
        findingaid = Findingaid.create! valid_attributes
        patch findingaid_url(findingaid), params: {findingaid: new_attributes}
        findingaid.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the findingaid" do
        findingaid = Findingaid.create! valid_attributes
        patch findingaid_url(findingaid), params: {findingaid: new_attributes}
        findingaid.reload
        expect(response).to redirect_to(findingaid_url(findingaid))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        findingaid = Findingaid.create! valid_attributes
        patch findingaid_url(findingaid), params: {findingaid: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested findingaid" do
      findingaid = Findingaid.create! valid_attributes
      expect {
        delete findingaid_url(findingaid)
      }.to change(Findingaid, :count).by(-1)
    end

    it "redirects to the findingaids list" do
      findingaid = Findingaid.create! valid_attributes
      delete findingaid_url(findingaid)
      expect(response).to redirect_to(findingaids_url)
    end
  end
end
