require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/slugmaps", pending: "Review", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Slugmap. As you add validations to Slugmap, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Slugmap.create! valid_attributes
      get slugmaps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      slugmap = Slugmap.create! valid_attributes
      get slugmap_url(slugmap)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_slugmap_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      slugmap = Slugmap.create! valid_attributes
      get edit_slugmap_url(slugmap)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Slugmap" do
        expect {
          post slugmaps_url, params: {slugmap: valid_attributes}
        }.to change(Slugmap, :count).by(1)
      end

      it "redirects to the created slugmap" do
        post slugmaps_url, params: {slugmap: valid_attributes}
        expect(response).to redirect_to(slugmap_url(Slugmap.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Slugmap" do
        expect {
          post slugmaps_url, params: {slugmap: invalid_attributes}
        }.not_to change(Slugmap, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post slugmaps_url, params: {slugmap: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested slugmap" do
        slugmap = Slugmap.create! valid_attributes
        patch slugmap_url(slugmap), params: {slugmap: new_attributes}
        slugmap.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the slugmap" do
        slugmap = Slugmap.create! valid_attributes
        patch slugmap_url(slugmap), params: {slugmap: new_attributes}
        slugmap.reload
        expect(response).to redirect_to(slugmap_url(slugmap))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        slugmap = Slugmap.create! valid_attributes
        patch slugmap_url(slugmap), params: {slugmap: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested slugmap" do
      slugmap = Slugmap.create! valid_attributes
      expect {
        delete slugmap_url(slugmap)
      }.to change(Slugmap, :count).by(-1)
    end

    it "redirects to the slugmaps list" do
      slugmap = Slugmap.create! valid_attributes
      delete slugmap_url(slugmap)
      expect(response).to redirect_to(slugmaps_url)
    end
  end
end
