bhl:
  name: 'University of Michigan Bentley Historical Library'
  about_url: https://bentley.umich.edu/
  description: 'The Bentley Historical Library collects the materials for and promotes the study of the histories of two great, intertwined institutions, the State of Michigan and the University of Michigan. The Library is open without fee to the public, and we welcome researchers regardless of academic or professional affiliation.'
  visit_note: ''
  building: ''
  address1: '1150 Beal Avenue'
  address2: ''
  city: 'Ann Arbor'
  state: 'MI'
  zip: '48109-2113'
  country: 'USA'
  phone: ''
  contact_info: 'bentley.ref@umich.edu'
  thumbnail_url: '/thumbnails/BHL-x400.jpg'
  repo_about:
    using_materials: 'Finding aids describe collections of primary sources and other unique, original, or rare materials. Some finding aids contain links to digitized versions of parts or all of a collection. Access to the original physical items, when available, requires requesting items for use in the reading room. Items may not be requested for use outside of the library.'
    visitor_info: 'The Bentley is open by appointment only Monday-Friday 10am - 4pm, including the general public. For more information, visit <a href="https://bentley.umich.edu/research/policies/">In-Person Research Policies</a>.'
    how_to_request: 'Please visit <a href="https://bentley.umich.edu/research/requesting-items-new2020/">Requesting Items</a>.'
    how_to_order: 'Please visit <a href="https://bentley.umich.edu/research/duplication/">Duplication of Materials</a>.'
  request_types:
    aeon_hidden_form_request:
      request_url: https://aeon.bentley.umich.edu/ead_request
      request_mappings:
        url_params:
          Action: 11
          Type: 200
        static:
          SystemId: ArcLight
#          ItemInfo1: manuscript
        accessor:
          ItemTitle: collection_name
          idno: eadid
          CallNumber: collection_unitid
          SubLocation: physloc
          ItemDate: collection_date
          ItemAuthor: collection_creator
        transform:
          ReferenceNumber:
            field: eadid
            regex: 'umich-bhl-(.*)'
  dlxs_iiif:
    image:
      - bhl
    text:
      - angell
      - blydenburgh
      - daas
      - hudson
      - mershon
      - petoskey
      - potter
      - pray
      - thomas
      - walker
  mivideo:
    partner_id: "1758271"
    uiconf_id: "51362482"
